spring:
  application:
    name: introduction-spring-cloud-stream

  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  cloud:
    function:
      definition: processor;consumer
    stream:
      output-bindings: producer
      bindings:
        processor-in-0:
          destination: my-process-topic
          group: consumer
          contentType: text/plain
          binder: rabbit
        processor-out-0:
          destination: my-result-topic
          group: consumer
          content-type: application/json
          binder: rabbit
        consumer-in-0:
          destination: my-result-topic
          group: consumer
          contentType: application/json
          binder: rabbit
        producer:
          destination: my-process-topic
          contentType: text/plain
          binder: rabbit
